name: Publish Python distributions to PyPI and TestPyPI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-n-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     directory: ./coverage/reports/
      #     env_vars: OS,PYTHON
      #     fail_ci_if_error: true
      #     files: ./coverage1.xml,./coverage2.xml
      #     flags: unittests
      #     name: codecov-umbrella
      #     path_to_write_report: ./coverage/codecov_report.txt
      #     verbose: true
      - name: Build binary wheel and a source tarball
        run: |
          pip install twine wheel
          python setup.py bdist_egg --exclude-source-files
          wheel convert dist/wolfgang-*.egg -d dist
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          skip_existing: true
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
